[FIX] account_invoice_tax: avoid including amount_currency when not needed
Fixed an issue in '_get_amount_updated_values' where 'amount_currency'
was included in the dictionary even when unnecessary,
causing errors when 'amount_company_currency' was set to 'None'.

Now, 'amount_currency' is only added if the move's currency differs
from the company currency and 'self.amount' is set.
This prevents operations involving 'None' values, avoiding errors when processing the data.

Reported error:

closes ingadhoc/account-invoicing#211

Typeerror: unsupported operand type(s) for -: 'float' and 'NoneType'
Signed-off-by: Camila Vives <cav@adhoc.com.ar>